### ISSUE TITLE
many-to-many relationship doesn't preserve shared context in nested loads

### ISSUE THREAD

**Issue by kurmetaubanov** [ash-project/ash#2159]
### Versions

elixir 1.18.1-otp-27
erlang 27.2

ash 3.5.23
ash_postgres 2.6.8
ash_sql 0.2.82

### Operating system

Ubuntu 24

### Current Behavior

Policies are set with checks using shared contexts

We can't fetch shared context in nested loads for resources acting as many-to-many bridge

### Reproduction

Reproduction: https://github.com/kurmetaubanov/ash_load_bug

1) Setup the project and click buttons to create users and to load users

2) You will see that users places couldn't be fetched

3) You can temporarily turn off read policies for EmployeePlace by uncommenting one line there, then you will see users places fetched okay

4) You can see debug log in iex console, how shared context dissapears at EmployeePlace action, and re-appears at Place action.

Thanks!

### Expected Behavior

Shared contexts should be in every action, including actions with resources that act as many-to-many bridges

**Comment by zachdaniel** [comment]
Fixed in cd3c019d077340f7c9e857ddc1e4f22dc5a844fc

**Comment by kurmetaubanov** [comment]
hi Zach, i have tested your fix but it still doesn't work for me

**Comment by kurmetaubanov** [comment]
https://github.com/user-attachments/assets/e19145ee-03d0-4b36-b834-997f25fc0969

the shared: %{info: info} or info: info are still missing in the context

i do match on shared: %{info: info}

**Comment by zachdaniel** [comment]
Ah, right. two things:

1. you caught a bug by doing it slightly incorrectly, thank you 😄 
2. shared context is copied "out" of shared context, so you should use `context[:place_permissions?]` as opposed to `context[:shared][:place_permissions?]`

**Comment by zachdaniel** [comment]
Fixed here: f91c98fe772bb17d9860b9a2b324d7fa89879b23

**Comment by kurmetaubanov** [comment]
Perfect!!! Thank you!
