### ISSUE TITLE
modify_query in read_action not applied in aggregation

### ISSUE THREAD

**Issue by TommasoAmici** [ash-project/ash#2195]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### AI Policy

- [x] I agree to follow this project's AI Policy, or I agree that AI was not used while creating this issue.

### Versions

ash 3.5.26
elixir 1.18
erlang 27

### Operating system

macos

### Current Behavior

I have a read action with `modify_query`. The action works correctly when used alone for reading resources.

I'm trying to use the same action in an aggregation, as documented here: https://hexdocs.pm/ash/dsl-ash-resource.html#aggregates-sum-read_action

but it seems the modify function is never called.

### Reproduction

I've added a test in my fork of ash here:

https://github.com/TommasoAmici/ash/commit/2deb568e6dc2da71a812b0730e044fb1f51c4fa1

### Expected Behavior

the query should be modified for aggregations as well as normal read actions

**Comment by zachdaniel** [comment]
@TommasoAmici I've pushed a fix to `main`. Can you please make a pull request with your tests to confirm that it works?

**Comment by TommasoAmici** [comment]
@zachdaniel I've opened a PR here: https://github.com/ash-project/ash/pull/2200

It seems this is still not working properly though :/
