### ISSUE TITLE
Actor not being passed from aggregate between resources

### ISSUE THREAD

**Issue by lifeofdan** [ash-project/ash#775]
**Describe the bug**
I am trying to use an actor in a calculation and then use that calculation in an aggregate on another resource but the actor is not being passed from the related resource.

**To Reproduce**
Create a calculation that depends on the actor being passed and then try to aggregate that calculation from a related resource. 

I have created a fork of the ash framework and added a test to showcase the issue. https://github.com/lifeofdan/ash

**Expected behavior**
I expected the actor to be passed between resources.

**Runtime**
 - Elixir version 1.15.4
 - Erlang version 26.0.2
 - OS MacOs
 - Ash version  2.17.0

**Comment by zachdaniel** [comment]
I will take a look tomorrow :)

**Comment by zachdaniel** [comment]
@lifeofdan when you first experienced this was it with the `ash_postgres` data layer?

**Comment by zachdaniel** [comment]
I've pushed something up to `ash` main that may resolve that issue if so. If you encountered the issue in `ash_postgres`, it would be great if you could add a test case reproducing this issue there too 🙇

**Comment by lifeofdan** [comment]
@zachdaniel, yes, we are using the `ash_postgres` data layer here at HereTask (my employer). I'll try to make a test case that reproduces the issue in the `ash_postgres` repo as well. 

You have fixed the issue I proposed in my initial test case, but it didn't solve my issue completely. I didn't model my issue in entirety because I thought fixing the above was the whole issue. Apologies for not getting it right the first time. :)

In the codebase I'm working on I'm using the aggregate from a calculation. So it is like there is a resource with a aggregate that a calculation is using and then another resource using the calculation (from the first resource) for it's aggregate and then using a calculation on that aggregate. It seems the calculation isn't passing the actor either. So I've updated my test in my fork to show this as well.

**Comment by zachdaniel** [comment]
I don't think I see the updated test in your fork. Last commit was 2 days ago

**Comment by lifeofdan** [comment]
It should be there now.
<img width="1175" alt="image" src="https://github.com/ash-project/ash/assets/1669918/047f934e-da49-4481-b138-b0c52bf718e6">

**Comment by zachdaniel** [comment]
Hey there! So it looks like this is actually a data layer bug that both ETS *and* AshPostgres shared. I've pushed something up to `ash_postgres` that I think should fix it, but haven't had a chance to test it. Mind trying it out?

**Comment by lifeofdan** [comment]
Absolutely, I'll try it out in the morning and let you know.

**Comment by lifeofdan** [comment]
@zachdaniel I've tested this in my fork, as well as in my work project and the issue seems to still exist, unfortunately.

**Comment by zachdaniel** [comment]
🤔 interesting. The test you added passes in the repo.

**Comment by zachdaniel** [comment]
🤔 Interesting, I was pretty sure I got your test passing from your fork.

**Comment by lifeofdan** [comment]
Sorry, I removed my comment in hope you wouldn't see it. I was incorrect about the test I put into my fork. The fork is definitely passing, so I now need to re-evaluate my work code as to what the problem really is.

**Comment by zachdaniel** [comment]
ah, okay gotcha. The fix for `ash_postgres` may not have worked. I need to go for the evening, but a failing test for `ash_postgres` would give me the ammunition to fix it there as well 🙇

**Comment by lifeofdan** [comment]
Yes, I'll look at `ash_postgres` today. I looked yesterday but was unable to get a proper test case working. Instead I was running into a different error in the `ash_postgres` codebase than what I was experiencing here.

**Comment by lifeofdan** [comment]
Thank you for your work so far. Very much appreciated. :)

**Comment by zachdaniel** [comment]
My pleasure. Also feel free to post if you have a new error from `ash_postgres` because maybe I'll be able to tell what's up :)

**Comment by lifeofdan** [comment]
This seems to have been resolved in `ash` but I'm still having issues that are related to `ash_postgres`. I am closing this issue as resolved for the `ash` part of things and will continue my issue in the `ash_postgres` repo. Tyvm. :)
