### ISSUE TITLE
Regression with AshPhoenix.Form.for_create since Ash v2.17.14

### ISSUE THREAD

**Issue by pierrelegall** [ash-project/ash#816]
**Description**

I experienced a regression on a migration from Ash `v2.17.13` (ok) to `v2.17.14` (ko).

**My use case**

This is a short liveview with some `dbg()`:

```elixir
defmodule MyApp.Live.EventCreate do
  @moduledoc """
  Event create live view.
  """

  use MyAppWeb, :live_view

  alias MyApp.Resources.Event
  alias MyApp.Api

  @impl true
  def render(assigns) do
    ~H"""
    [...]
    """
  end

  @impl true
  def mount(_params, _session, socket) do
    form =
      AshPhoenix.Form.for_create(
        Event,
        :create,
        api: Api,
        prepare_source: fn changeset ->
          changeset
          |> Ash.Changeset.manage_relationship(
            :creator,
            socket.assigns.current_user,
            type: :append_and_remove
          )
          |> dbg() # SEEMS OK, NO ERROR
        end
      )
      |> dbg() # SOME EXPECTED ERRORS, BUT UNEXPECTED ERRORS ABOUT THE CREATOR
      |> to_form()

    {:ok, assign(socket, :form, form)}
  end
end
```

In the second `dbg()` output, I got unexpected errors about the creator I don't have with Ash `v2.17.13`:

```elixir
       errors: [
         %Ash.Error.Changes.InvalidAttribute{
           field: :creator_id,
           message: "exactly %{exactly} of %{keys} must be present",
           private_vars: nil,
           value: nil,
           changeset: nil,
           query: nil,
           error_context: [],
           vars: [
             fields: [:creator, :creator_id],
             keys: "creator,creator_id",
             attributes: [:creator, :creator_id],
             exactly: 1
           ],
           path: [],
           stacktrace: #Stacktrace<>,
           class: :invalid
         },
         %Ash.Error.Changes.InvalidAttribute{
           field: :creator,
           message: "exactly %{exactly} of %{keys} must be present",
           private_vars: nil,
           value: #Ash.NotLoaded<:relationship>,
           changeset: nil,
           query: nil,
           error_context: [],
           vars: [
             fields: [:creator, :creator_id],
             keys: "creator,creator_id",
             attributes: [:creator, :creator_id],
             exactly: 1
           ],
           path: [],
           stacktrace: #Stacktrace<>,
           class: :invalid
         }
       ]
```

**Expected behavior**

I suppose it should work the same as with Ash `v2.17.13`.

**Runtime**

 - Elixir: `v1.15.7`
 - Erlang: `v26.2.1`
 - OS: Archlinux, Linux `6.6.8-arch1` 
 - Ash: reproducted with `v2.17.14` & `v2.17.17`, but works well with `v2.17.13`
 - Ash Phoenix: `v1.2.24`

PS: maybe this should be post in https://github.com/ash-project/ash_phoenix instead?

**Comment by zachdaniel** [comment]
What errors did you have in the previous version?

**Comment by pierrelegall** [comment]
The complete liveview:

```elixir
defmodule DjoWeb.Live.EventCreate do
  @moduledoc """
  Event create live view.
  """

  use DjoWeb, :live_view

  alias Djo.Resources.Event
  alias Djo.Api

  on_mount {MyAppWeb.Hooks.LiveAuthentication, :logged_in_user_required}

  @impl true
  def render(assigns) do
    ~H"""
    <h2>Create an event</h2>
    <.simple_form
      id="event-create-form"
      for={@form}
      as="event"
      phx-change="validate"
      phx-submit="save"
    >
      <.input name="event[name]" field={@form[:name]} label="Name" phx-debounce />
      <.input name="event[description]" field={@form[:description]} label="Description" phx-debounce />
      <.input
        name="event[begin_at]"
        field={@form[:begin_at]}
        type="datetime-local"
        label="Begin"
        phx-debounce
      />
      <.input
        name="event[end_at]"
        field={@form[:end_at]}
        type="datetime-local"
        label="End"
        phx-debounce
      />
      <:actions>
        <.button>Save</.button>
      </:actions>
    </.simple_form>
    """
  end

  @impl true
  def mount(_params, _session, socket) do
    form =
      AshPhoenix.Form.for_create(
        Event,
        :create,
        api: Api,
        prepare_source: fn changeset ->
          changeset
          |> Ash.Changeset.manage_relationship(
            :creator,
            socket.assigns.current_user,
            type: :append_and_remove
          )
        end
      )
      |> to_form()

    {:ok, assign(socket, :form, form)}
  end

  @impl true
  def handle_event("validate", %{"event" => inputs}, socket) do
    form = AshPhoenix.Form.validate(socket.assigns.form, inputs)

    {:noreply, assign(socket, :form, form)}
  end

  @impl true
  def handle_event("save", %{"event" => inputs}, socket) do
    case AshPhoenix.Form.submit(socket.assigns.form, params: inputs) do
      {:ok, event} ->
        {:noreply, push_navigate(socket, to: ~p"/events/#{event.unique_name}")}

      {:error, form_with_errors} ->
        {:noreply, assign(socket, :form, form_with_errors)}
    end
  end
end
```

And the previous errors below was expected, because its come from empty fields just after mount:

```elixir
[lib/djo_web/live/event_create_live.ex:63: DjoWeb.Live.EventCreate.mount/3]
AshPhoenix.Form.for_create(
  Event,
  :create,
  api: Api,
  prepare_source: fn changeset ->
    changeset
    |> Ash.Changeset.manage_relationship(
      :creator,
      socket.assigns.current_user,
      type: :append_and_remove
    )
  end
) #=> #AshPhoenix.Form<
  resource: Djo.Resources.Event,
  action: :create,
  type: :create,
  params: %{},
  source: #Ash.Changeset<
    action_type: :create,
    action: :create,
    attributes: %{image_ids: %{}},
    relationships: %{
      creator: [
        {[
           #Djo.Resources.User<
             __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
             id: "d819d840-d0af-4f7b-9b5c-39b7f79ad402",
             name: "Alice",
             unique_name: "alice",
             email: #Ash.CiString<"alice@djo.art">,
             image_ids: %{"avatar" => "cfb1541f-71ef-409d-b227-de1fa52b2ede"},
             aggregates: %{},
             calculations: %{},
             ...
           >
         ],
         [
           ignore?: false,
           on_missing: :unrelate,
           on_match: :ignore,
           on_lookup: :relate,
           on_no_match: :error,
           eager_validate_with: false,
           authorize?: true,
           type: :append_and_remove,
           meta: [inputs_was_list?: false]
         ]}
      ]
    },
    arguments: %{},
    errors: [ # <= ERRORS HERE
      %Ash.Error.Changes.Required{
        field: :end_at,
        type: :attribute,
        resource: Djo.Resources.Event,
        changeset: nil,
        query: nil,
        error_context: [],
        vars: [],
        path: [],
        stacktrace: #Stacktrace<>,
        class: :invalid
      },
      %Ash.Error.Changes.Required{
        field: :begin_at,
        type: :attribute,
        resource: Djo.Resources.Event,
        changeset: nil,
        query: nil,
        error_context: [],
        vars: [],
        path: [],
        stacktrace: #Stacktrace<>,
        class: :invalid
      },
      %Ash.Error.Changes.Required{
        field: :unique_name,
        type: :attribute,
        resource: Djo.Resources.Event,
        changeset: nil,
        query: nil,
        error_context: [],
        vars: [],
        path: [],
        stacktrace: #Stacktrace<>,
        class: :invalid
      },
      %Ash.Error.Changes.Required{
        field: :name,
        type: :attribute,
        resource: Djo.Resources.Event,
        changeset: nil,
        query: nil,
        error_context: [],
        vars: [],
        path: [],
        stacktrace: #Stacktrace<>,
        class: :invalid
      }
    ],
    data: #Djo.Resources.Event<
      artists: #Ash.NotLoaded<:relationship>,
      links: #Ash.NotLoaded<:relationship>,
      bookings: #Ash.NotLoaded<:relationship>,
      place: #Ash.NotLoaded<:relationship>,
      creator: #Ash.NotLoaded<:relationship>,
      artists_join_assoc: #Ash.NotLoaded<:relationship>,
      __meta__: #Ecto.Schema.Metadata<:built, "events">,
      id: nil,
      name: nil,
      unique_name: nil,
      description: nil,
      begin_at: nil,
      end_at: nil,
      image_ids: nil,
      created_at: nil,
      updated_at: nil,
      creator_id: nil,
      place_id: nil,
      aggregates: %{},
      calculations: %{},
      ...
    >,
    valid?: false
  >,
  name: "form",
  data: nil,
  form_keys: [],
  forms: %{},
  api: Djo.Api,
  method: "post",
  submit_errors: nil,
  id: "form",
  transform_errors: nil,
  original_data: nil,
  transform_params: nil,
  prepare_params: nil,
  prepare_source: #Function<0.44794752/1 in DjoWeb.Live.EventCreate.mount/3>,
  warn_on_unhandled_errors?: true,
  any_removed?: false,
  added?: false,
  changed?: false,
  touched_forms: MapSet.new([]),
  valid?: false,
  errors: nil,
  submitted_once?: false,
  just_submitted?: false,
  ...
>
```

**Comment by zachdaniel** [comment]
Some potentially related bugs were fixed in `1.2.25`. Can you try that and see if you are getting the same error?

**Comment by zachdaniel** [comment]
Will close for now, but please reopen if it didn't resolve your issue.

**Comment by pierrelegall** [comment]
Still the same problem with:

- `ash`: `v2.17.14` & `v2.17.19`
- `ash_phoenix`: `v1.2.25`

And still no problem with:

- `ash`: `v2.17.13`
- `ash_phoenix`: `v1.2.25`

**Comment by pierrelegall** [comment]
To be (maybe) clearer, I put my `dbg()` here:

```elixir
  @impl true
  def handle_event("save", %{"event" => inputs}, socket) do
    case AshPhoenix.Form.submit(socket.assigns.form, params: inputs) |> dbg() do # <- HERE
      {:ok, event} ->
        {:noreply, push_navigate(socket, to: ~p"/events/#{event.unique_name}")}

      {:error, form_with_errors} ->
        {:noreply, assign(socket, :form, form_with_errors)}
    end
  end
```

When the fields are filled properly save is trigger, then the output is:

```elixir
DjoWeb.Live.EventCreate.handle_event/3]
AshPhoenix.Form.submit(socket.assigns.form, params: inputs) #=> {:error,
 %Phoenix.HTML.Form{
   source: #AshPhoenix.Form<
     resource: Djo.Resources.Event,
     action: :create,
     type: :create,
     params: %{
       "begin_at" => "2024-01-03 08:00:14.979258Z",
       "description" => "New description",
       "end_at" => "2024-01-04 08:00:14.979258Z",
       "name" => "New name"
     },
     source: #Ash.Changeset<
       action_type: :create,
       action: :create,
       attributes: %{
         name: "New name",
         description: "New description",
         image_ids: %{},
         unique_name: "new-name",
         begin_at: ~U[2024-01-03 08:00:14Z],
         end_at: ~U[2024-01-04 08:00:14Z]
       },
       relationships: %{
         creator: [
           {[
              #Djo.Resources.User<
                __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
                id: "9e7492db-f581-473e-bd08-dd316afa1314",
                name: "U7747",
                unique_name: "u7747",
                email: #Ash.CiString<"u7747@example.com">,
                image_ids: %{},
                aggregates: %{},
                calculations: %{},
                ...
              >
            ],
            [
              ignore?: false,
              on_missing: :unrelate,
              on_match: :ignore,
              on_lookup: :relate,
              on_no_match: :error,
              eager_validate_with: false,
              authorize?: true,
              type: :append_and_remove,
              meta: [inputs_was_list?: false]
            ]}
         ]
       },
       arguments: %{},
       errors: [
         %Ash.Error.Changes.InvalidAttribute{
           field: :creator_id,
           message: "exactly %{exactly} of %{keys} must be present",
           private_vars: nil,
           value: nil,
           changeset: nil,
           query: nil,
           error_context: [],
           vars: [
             fields: [:creator, :creator_id],
             keys: "creator,creator_id",
             attributes: [:creator, :creator_id],
             exactly: 1
           ],
           path: [],
           stacktrace: #Stacktrace<>,
           class: :invalid
         },
         %Ash.Error.Changes.InvalidAttribute{
           field: :creator,
           message: "exactly %{exactly} of %{keys} must be present",
           private_vars: nil,
           value: #Ash.NotLoaded<:relationship>,
           changeset: nil,
           query: nil,
           error_context: [],
           vars: [
             fields: [:creator, :creator_id],
             keys: "creator,creator_id",
             attributes: [:creator, :creator_id],
             exactly: 1
           ],
           path: [],
           stacktrace: #Stacktrace<>,
           class: :invalid
         }
       ],
       data: #Djo.Resources.Event<
         artists: #Ash.NotLoaded<:relationship>,
         links: #Ash.NotLoaded<:relationship>,
         bookings: #Ash.NotLoaded<:relationship>,
         place: #Ash.NotLoaded<:relationship>,
         creator: #Ash.NotLoaded<:relationship>,
         artists_join_assoc: #Ash.NotLoaded<:relationship>,
         __meta__: #Ecto.Schema.Metadata<:built, "events">,
         id: nil,
         name: nil,
         unique_name: nil,
         description: nil,
         begin_at: nil,
         end_at: nil,
         image_ids: nil,
         created_at: nil,
         updated_at: nil,
         creator_id: nil,
         place_id: nil,
         aggregates: %{},
         calculations: %{},
         ...
       >,
       context: %{actor: nil, authorize?: false},
       valid?: false
     >,
     name: "form",
     data: nil,
     form_keys: [],
     forms: %{},
     api: Djo.Api,
     method: "post",
     submit_errors: [
       creator_id: {"exactly %{exactly} of %{keys} must be present",
        [keys: "creator,creator_id", exactly: 1]},
       creator: {"exactly %{exactly} of %{keys} must be present",
        [keys: "creator,creator_id", exactly: 1]}
     ],
     id: "form",
     transform_errors: nil,
     original_data: nil,
     transform_params: nil,
     prepare_params: nil,
     prepare_source: #Function<0.11503288/1 in DjoWeb.Live.EventCreate.mount/3>,
     warn_on_unhandled_errors?: true,
     any_removed?: false,
     added?: false,
     changed?: true,
     touched_forms: MapSet.new(["begin_at", "description", "end_at", "name"]),
     valid?: false,
     errors: true,
     submitted_once?: true,
     just_submitted?: true,
     ...
   >,
   impl: Phoenix.HTML.FormData.AshPhoenix.Form,
   id: "form",
   name: "form",
   data: nil,
   hidden: [_touched: "begin_at,description,end_at,name", _form_type: "create"],
   params: %{
     "begin_at" => "2024-01-03 08:00:14.979258Z",
     "description" => "New description",
     "end_at" => "2024-01-04 08:00:14.979258Z",
     "name" => "New name"
   },
   errors: [
     creator_id: {"exactly %{exactly} of %{keys} must be present",
      [keys: "creator,creator_id", exactly: 1]},
     creator: {"exactly %{exactly} of %{keys} must be present",
      [keys: "creator,creator_id", exactly: 1]}
   ],
   options: [method: "post"],
   index: nil,
   action: nil
 }}
```

**Comment by zachdaniel** [comment]
I'm having trouble figuring out what this could be. Could you please see if you can replicate this when just submitting the action directly? i.e take the `params` you're submitting to the action, and call the action directly in the broken version and in the new version? That will help me isolate the issue to `ash_phoenix` or `ash` core.

**Comment by pierrelegall** [comment]
The experience, with Ash `v2.17.20`:

```elixir
defmodule DjoWeb.Live.ArtistCreate do
  @moduledoc """
  Artist create live view.
  """

  use DjoWeb, :live_view

  alias Djo.Resources.Artist
  alias Djo.Api

  on_mount {DjoWeb.Hooks.LiveAuthentication, :logged_in_user_required}

  @impl true
  def render(assigns) do
    ~H"""
    <h2>Create an artist</h2>
    <.simple_form id="artist-create-form" for={@form} phx-change="validate" phx-submit="save">
      <.input name="artist[name]" field={@form[:name]} label="Name" phx-debounce />
      <.input name="artist[description]" field={@form[:description]} label="Description" phx-debounce />
      <:actions>
        <.button>Save</.button>
      </:actions>
    </.simple_form>
    """
  end

  @impl true
  def mount(_params, _session, socket) do
    form =
      AshPhoenix.Form.for_create(
        Artist,
        :create,
        api: Api
        ### --- Disabled for the test purpose ---
        # prepare_source: fn changeset ->
        #   changeset
        #   |> Ash.Changeset.manage_relationship(
        #     :creator,
        #     socket.assigns.current_user,
        #     type: :append_and_remove
        #   )
        # end
      )
      |> to_form()

    {:ok, assign(socket, :form, form)}
  end

  @impl true
  def handle_event("validate", %{"artist" => input}, socket) do
    form = AshPhoenix.Form.validate(socket.assigns.form, input)

    {:noreply, assign(socket, :form, form)}
  end

  @impl true
  def handle_event("save", %{"artist" => input}, socket) do
    ### --- Workaround of the `prepare_source` disabling ---
    input =
      input
      |> Map.put_new("creator", socket.assigns.current_user)

    ### --- `dbg()` below ---
    case AshPhoenix.Form.submit(socket.assigns.form, params: input) |> dbg() do
      {:ok, artist} ->
        {:noreply, push_navigate(socket, to: ~p"/artists/#{artist.unique_name}")}

      {:error, form_with_errors} ->
        {:noreply, assign(socket, :form, form_with_errors)}
    end
  end
end
```

My tests pass with this `dbg()` output:

```elixir
[lib/djo_web/live/artist_create_live.ex:62: DjoWeb.Live.ArtistCreate.handle_event/3]
AshPhoenix.Form.submit(socket.assigns.form, params: input) #=> {:ok,
 #Djo.Resources.Artist<
   events: #Ash.NotLoaded<:relationship>,
   links: #Ash.NotLoaded<:relationship>,
   bookings: #Ash.NotLoaded<:relationship>,
   creator: #Djo.Resources.User<
     __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
     id: "be70f4f3-30bc-425d-aa67-9235bfbbdc31",
     name: "U3140",
     unique_name: "u3140",
     email: #Ash.CiString<"u3140@example.com">,
     image_ids: %{},
     aggregates: %{},
     calculations: %{},
     ...
   >,
   events_join_assoc: #Ash.NotLoaded<:relationship>,
   __meta__: #Ecto.Schema.Metadata<:loaded, "artists">,
   id: "23a9a65a-673d-4475-ae0e-cc92de0292d0",
   name: "New name",
   unique_name: "new-name",
   description: "New description",
   image_ids: %{},
   created_at: ~U[2024-01-05 16:27:08.641299Z],
   updated_at: ~U[2024-01-05 16:27:08.641299Z],
   creator_id: "be70f4f3-30bc-425d-aa67-9235bfbbdc31",
   aggregates: %{},
   calculations: %{},
   ...
 >}
```

**Comment by zachdaniel** [comment]
Oh, how interesting. So it only breaks when you use `prepare_source`???

**Comment by zachdaniel** [comment]
CI is releasing `v2.17.21` with the fix. Thanks for the report!

**Comment by pierrelegall** [comment]
Tested and validated :partying_face:

Thank you for the fix!
